deploy:
  provider: pypi
  user: __token__
  password:
    secure: Z3Lzorb1PnY/V3hqPRDioSfLN5fMg0gZHirOkEc2A6jxQAkEu1CCSuaJ/TS2FLu8MaG31akkp7SqTqAt9opDqhZ4hbeF8QErDol1oIUXg4AtmjYXw91K52D047F5s50J+vb8P6ICPHZrIbd/Z07FdIsgRvsxJrZOP7CzVaoBOXJxGei8+b7IDlpju9eR1p6syRUdVY6hZZPCUpZsmZVJXELC+a1NkCRj3r1n2vxGGsktE5TPltREo3yfH4CWKL+xdINRvKfcU+6C5w8VQMq5gSe+OuZPkHTnoRG3XUYJDuP8K9a8I0YL1C6fJNjAepWbs3igrUDJTHgNpCawMGPVBFGIr6nQfwv+sjR5j9W7/OHc4pdqbs7ho7x0Zk3AxroBwScflTV66iSbOHEjyUsm9b8WFrDbx+mfg/q2mwB/zoZ53Kf6oPgGdJO94bBrGXIhZBCXFc0SPmKUwN7tiNTL8JbUz2NnngacFM4ab7Qforgy2jTvRSW6aJnRVOsS48JitgYKbl+/S/qTmh45hbXkPmqM6OKWRBrYGnKQIiGflLCUrDyHJAhsNqjQt1PTR75Fa5YxoYTFeRTd7mKZh2U6o1cLvU31vT1TehMc4tZUfYWHldAd5O0XFRY2v81aO8g8Ue1pJSJn8Qr074Zv1yrCOhn2/bu7kCC0ea3W/vvOD+A=
  on:
    tags: true
